Add Task1
KotukovaEL/Test-task pull request #1
Opened 2023-04-02 19:02 UTC by KotukovaEL

2023-04-02 19:05 UTC, KuzminDS requested changes

2023-04-02 19:05 UTC, KuzminDS commented on Task1/Task1_1/Program.cs
> +            Console.WriteLine("Hello World!");
А где задание???

2023-04-03 15:56 UTC, KuzminDS requested changes

2023-04-03 15:56 UTC, KuzminDS commented on Task2/Task1_2/Program.cs
> +                for (int j = 1; j <= i; j++)
У класса string есть конструктор, который позволяет один символ продублировать несколько раз подряд в одной строке. new string("*", i). То есть можно избавиться от вложенного цикла, и вместо сложности O(n^2) получить O(n).

2023-04-03 15:56 UTC, KuzminDS commented on Task2/Task1_2/Program.cs
> +            int n = int.Parse(Console.ReadLine());
А если я введу строку 'aslkdjlkf'???))) Что будет?

2023-04-03 15:56 UTC, KuzminDS commented on Task3/Task1_3/Program.cs
> +            {
Аналогичные замечания, как и в 1.1.2

2023-04-03 15:56 UTC, KuzminDS commented on Task4/Task1_4/Program.cs
> +                Triangle(i, n);
За это лайк, всегда старайся разбивать код на методы, чтобы было более читаемо. Но метод должен начинаться с глагола, поэтому можно назвать PrintTriangle

2023-04-03 15:56 UTC, KuzminDS commented on Task4/Task1_4/Program.cs
> +            int n = int.Parse(Console.ReadLine());
Надо бы сделать отдельный метод, который будет ждать корректного ввода и (или) просто выводить ошибку по типу $"Некорректное целое значение '{value}'".

2023-04-03 15:56 UTC, KuzminDS commented on Task4/Task1_4/Program.cs
> +            for (int i = 1; i <= n; i++)
Тоже самое с конструктором string

2023-04-03 15:57 UTC, KuzminDS requested changes

2023-04-03 15:57 UTC, KuzminDS commented on Task1/Task1_1/Program.cs
> +            double a = double.Parse(Console.ReadLine());
Попробуй использовать метод TryParse

2023-04-03 16:51 UTC, KotukovaEL commented on Task2/Task1_2/Program.cs
> +            int n = int.Parse(Console.ReadLine());
ошибка вылетит)

2023-04-03 17:06 UTC, KuzminDS requested changes

2023-04-03 17:06 UTC, KuzminDS commented on Task7/Task1_7/Program.cs
> +            int[] massiv = Random(20, 1, 10);
Метод должен начинаться с глагола. Например, GenerateArray. Random не подойдет, потому что не понятно что это означает. Название метода должно уже четко говорить о том, какое действие мне надо ожидать от этого метода.

Плюс нельзя использовать транслиты. Если massiv прочитает англоязычный коллега, то он ничего не поймет. Просто array

2023-04-03 17:06 UTC, KuzminDS commented on Task7/Task1_7/Program.cs
> +            Sorting(massiv);
Sorting - это не глагол, а процесс. Поэтому можно просто назвать Sort

2023-04-03 17:06 UTC, KuzminDS commented on Task7/Task1_7/Program.cs
> +            }
Для этого можно сделать отдельный метод PrintArray, например. Потому что много логики лежит в одном Main методе, надо бы разбить на несколько методов. Я хочу читать методы как статью, где сначала описываются главные вещи, а затем только идут детали (в данном случае мне не интересно, как массив выводится, я хочу просто видеть, что вызвался метод, который куда-то там выведет массив. А если я захочу увидеть детали (логику) вывода массива, то загляну в соответствующий метод (PrintArray).)

2023-04-03 17:06 UTC, KuzminDS commented on Task7/Task1_7/Program.cs
> +            Console.WriteLine("\nМаксимальное значение массива: " + massiv[massiv.Length-1]);
А если ты забудешь до этого вызвать Sort ? Да, так эффективнее, чем запускать новый метод и искать max или min. Но надо подумать о читаемости: мне нужно выше подняться, чтобы понять смысл почему ты выбираешь именно эти индексы. И еще есть момент: Код выше могут поменять (например, сортировать в другом порядке), а данные 2 строчки забудут поменять, и получится неверное поведение. Поэтому стоит данную логику вынести в отдельные методы (либо можно подумать и обыграть как-нибудь по-другому).

2023-04-03 17:06 UTC, KuzminDS commented on Task7/Task1_7/Program.cs
> +                    //Console.Write(massiv[i] + " ");
Комментарии в таком виде не рекомендуется пушить.

2023-04-03 17:06 UTC, KuzminDS commented on Task7/Task1_7/Program.cs
> +            static int[] Sorting(int[] massiv)
Пузырек засчитываю. Но можешь почитать или посмотреть видосики как работает быстрая сортировка Quick Sort. Пузырек отработает за O(n^2), а быстрая сортировка гораздо быстрее (за O(n * log n) разберись почему).

2023-04-03 17:06 UTC, KuzminDS commented on Task7/Task1_7/Program.cs
> +                return massiv;
Снова транслит )

2023-04-07 16:24 UTC, KuzminDS commented on Task10/Task1_10/Program.cs
> +                Console.WriteLine();
Лишний WriteLine

2023-04-07 16:24 UTC, KuzminDS commented on Task10/Task1_10/Program.cs
> +            int[,] array = new int[4, 3];
Почему 4 и 3, а не 7 и 5? )) Подобный случай называется "магические значения". Никогда так не делай. Лучше сделай 2 аргумента в методе дополнительных, например, int dimention1, int dimention2 (в таком случае цифры в названии аргументов/переменных использовать можно). И передавай извне конкретные значения размерности.

2023-04-07 16:24 UTC, KuzminDS commented on Task10/Task1_10/Program.cs
> +                    if ((i+j)%2== 0)
пробелов не хватает между операциями)

2023-04-07 16:24 UTC, KuzminDS commented on Task5/Task1_5/Program.cs
> +                if (i % 3 == 0 || i % 5 == 0)
Самый простой вариант. Я бы тоже так сделал и не заморачивался) Еще есть вариант использовать более сложные формулы для более быстрого прохода от 1 до 1000, но с читаемостью могут быть проблемы) Так что оставляй как есть.

2023-08-15 17:48 UTC, KuzminDS commented on Task1/Task1_1.Tests/LogicTests.cs
> +        public void Should_calculate_square_corretly()
Название метода исправить

2023-08-15 17:48 UTC, KuzminDS commented on Task3/Task1_3/Logic.cs
> +                for (int j = n; j >= i; j--)
Сделать через конструктор string

2023-08-15 17:48 UTC, KuzminDS commented on Task4/Task1_4/Program.cs
> +            for (int i = 1; i <= n; i++)
перенести цикл в PrintTriangle

2023-08-15 17:48 UTC, KuzminDS commented on Task9/Task1_9.Tests/LogicTests.cs
> +        public void Should_find_sum_correctly()
Некорректный тест, исправить

2023-08-19 19:01 UTC, merged